### ISSUE TITLE
lasso man?

### ISSUE THREAD

**Issue by MasterEvilAce** [0xjclar/MoreMonsters#2]
We added this mod to our pack last night and we had a lasso man spawn. I didn't see anything in the readme or code referencing the lasso man... so I'm wondering how this could have happened? For our last quota I increased the spawn rate and monster count slowly over time. Unsure if this somehow triggered it.

The lasso man just chased/followed people and could not kill them (as he is supposedly not finished in code.)

Wondering if the MoreMonsters dev has any more insight on this...

**Comment by 0xjclar** [comment]
That was not intentional haha. Interesting.

Honestly I'm still not sure even after looking at the code. My only guess is its due to the way I limited how many of each individual monster could spawn, but even in that scenario you'd think lasso man would appear early.

Currently working on individual mob customization that should prevent this from happening.

**Comment by 0xjclar** [comment]
Figured out why.

On Titan at least, LassoMan is actually a part of the list of available entities to spawn. I'm guessing that the chance of him spawning is 0 with regards to the game's natural spawning, but this mod forcibly spawns in monsters via the list of enemies to spawn, resulting in him spawning.

This is fixed now, as this latest update I recently posted enables you to change the quantity for each type of monster, not just the same limit for each.
